---
apiVersion: v1
kind: Service
metadata:
  name: gluster-cluster
  namespace: registry
spec:
  ports:
  - port: 1

---
apiVersion: v1
kind: Endpoints
metadata:
  name: gluster-cluster
  namespace: registry
subsets:
- addresses:
  - ip: 192.168.1.5
  ports:
  - port: 1
