---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
    component: registry

spec:
  selector:
    app: registry
    component: registry

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
    component: registry

spec:
  selector:
    matchLabels:
      app: registry
      component: registry

  template:
    metadata:
      labels:
        app: registry
        component: registry

    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: registry
          mountPath: /var/lib/registry

      volumes:
      - name: registry
        glusterfs:
          endpoints: gluster-cluster
          path: registry
