---
apiVersion: v1
kind: Pod
metadata:
  name: rescue
  namespace: registry

spec:
  containers:
  - name: rescue
    image: busybox

    # Hold the container open, without running more exotic processes
    # You can exec into the container and debug state from within
    command: ["cat"]
    stdin: true

    volumeMounts:
    - mountPath: /var/lib/registry
      name: registry

  volumes:
  - name: registry
    glusterfs:
      endpoints: gluster-cluster
      path: registry
