apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    name: webapp

spec:
  selector:
    name: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

  # Add static routes on your external loadbalancers for this to work
  #   ip route add 10.1.0.0/16 via $NodeIP metric $x
  # kube-proxy will setup some DNAT rules for external traffic to reach the service
  externalIPs:
    - 10.1.0.100
