---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:  # ignored?
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: portage.condi.me
    path: "/usr/portage"
