---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
  namespace: gentoo

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: gentoo

spec:
  capacity:  # ignored?
    storage: 1Mi
  accessModes:
    - ReadWriteMany

  nfs:
    # Not available outside my network, use your own
    server: portage.condi.me
    path: "/usr/portage"
