apiVersion: apps/v1
kind: Deployment

metadata:
  name: stateful-db
  labels:
    name: stateful-db

spec:
  selector:
    matchLabels:
      app: stateful-db

  template:
    metadata:
      labels:
        app: stateful-db

    spec:
      containers:
      - name: db
        image: postgres
        volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgres

      volumes:
      - name: postgres
        emptyDir: {}
