apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stateful-web
  labels:
    name: stateful-web
spec:
  template:
    metadata:
      labels:
        app: stateful-web
    spec:
      containers:
      - name: stateful-web
        image: stateful:50-stateful
        env:
          - name: DATABASE_URL
            value: "postgres://postgres@10.0.0.2/postgres"
