apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stateful-db
  labels:
    name: stateful-db
spec:
  template:
    metadata:
      labels:
        app: stateful-db
    spec:
      containers:
      - name: db
        image: postgres
