apiVersion: v1
kind: Service
metadata:
  name: stateful-db
  labels:
    name: stateful-db
spec:
  selector:
    app: stateful-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
