apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
  labels:
    name: hello
spec:
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: hello:20-deploy
