apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog
  labels:
    name: blog
    app: blog

spec:
  template:
    metadata:
      labels:
        name: blog
        app: blog
    spec:
      containers:
      - name: blog
        image: bencord0/blog
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: blog-env
        livenessProbe:
          httpGet:
            path: /
            port: 8000
