apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    name: blog
    app: blog

spec:
  selector:
    matchLabels:
      name: blog
      app: blog

  template:
    metadata:
      labels:
        name: blog
        app: blog
    spec:
      containers:
      - name: blog
        image: bencord0/blog
        args:
        - -b
        - 0.0.0.0:8000
        - --access-logfile
        - '-'
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: blog-env
        - secretRef:
            name: blog-sec
            optional: true
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        volumeMounts:
        - name: conf
          mountPath: /conf
      volumes:
      - name: conf
        hostPath:
          path: /srv/conf
