apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres
    app: blog

spec:
  clusterIP: 10.0.228.16
  ports:
    - port: 5432
  selector:
    name: postgres
    app: blog
