apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    name: postgres
    app: blog

spec:
  template:
    metadata:
      labels:
        name: postgres
        app: blog

    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgdata
          emptyDir: {}
