---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: blog
  name: user
roleRef:
  kind: Role
  name: user
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: oidc:kubernetes-users
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: blog
  name: user
rules:
- apiGroups: [""]
  resources: ["configmaps", "pods", "pods/portforward", "replicationcontrollers", "services"]
  verbs: ["create", "delete", "get", "list", "proxy", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
  verbs: ["create", "delete", "get", "list", "proxy", "update", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["create", "delete", "get", "list", "proxy", "update", "watch"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["create", "delete", "get", "list", "proxy", "update", "watch"]
- apiGroups: ["extensions"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["create", "delete", "get", "list", "proxy", "update", "watch"]
