apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rproxy
  labels:
    name: rproxy
    app: blog

spec:
  template:
    metadata:
      labels:
        name: rproxy
        app: blog

    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: rproxy
        image: bencord0/rproxy
        ports:
        - name: web
          containerPort: 80
          hostPort: 80
          protocol: TCP
        - name: secureweb
          containerPort: 443
          hostPort: 443
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /conf
      volumes:
      - name: conf
        hostPath:
          path: /srv/conf
