apiVersion: apps/v1
kind: Deployment

metadata:
  name: picker
  labels:
    name: picker

spec:
  selector:
    matchLabels:
      app: picker

  template:
    metadata:
      labels:
        app: picker

    spec:
      containers:
      - name: picker
        image: registry.condi.me/picker:40-picker
        env:
        - name: DATABASE_URL
          value: "postgres://postgres@localhost/postgres"
        ports:
        - containerPort: 80

      - name: db
        image: postgres
