---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: default-readall

rules:
- apiGroups: [""]  # Core API group
  verbs: ["get", "watch", "list"]
  resources:
  - pods
  - replicationcontrollers
  - services
- apiGroups: ["apps"]
  verbs: ["get", "watch", "list"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
- apiGroups: ["autoscaling"]
  verbs: ["get", "watch", "list"]
  resources:
  - horizontalpodautoscalers
- apiGroups: ["batch"]
  verbs: ["get", "watch", "list"]
  resources:
  - cronjobs
  - jobs
- apiGroups: ["extensions"]
  verbs: ["get", "watch", "list"]
  resources:
  - daemonsets
  - deployments
  - replicasets
