---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: default-readall
roleRef:
  kind: Role
  name: default-readall
  apiGroup: rbac.authorization.k8s.io

subjects:
- kind: Group
  name: condi.me
  apiGroup: rbac.authorization.k8s.io

