---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: basic

rules:
- apiGroups: [""]
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
  resources:
  - configmaps
  - endpoints
  - pods
  - pods/attach
  - pods/exec
  - pods/log
  - pods/portforward
  - pods/proxy
  - pods/status
  - replicationcontrollers
  - replicationcontrollers/scale
  - replicationcontrollers/status
  - services
  - services/proxy

- apiGroups: ["batch", "extensions"]
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - post
  - update
  - watch
  resources:
  - deployments
  - jobs
  - replicasets
