---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: basic

rules:
- apiGroups: [""]
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - proxy
  - update
  - watch
  resources:
  - configmaps
  - endpoints
  - pods
  - pods/exec
  - pods/log
  - pods/portforward
  - services

- apiGroups: ["batch", "extensions"]
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - post
  - update
  - watch
  resources:
  - deployments
  - jobs
  - replicasets
