---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: basic

rules:
- apiGroups: [""]
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - proxy
  - update
  - watch
  resources:
  - pods
  - pods/portforward

- apiGroups: ["extensions"]
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - post
  - watch
  resources:
  - deployments
