---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: basic
roleRef:
  kind: Role
  name: basic
  apiGroup: rbac.authorization.k8s.io

subjects:
- kind: Group
  name: condi.me
  apiGroup: rbac.authorization.k8s.io
