---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:node
roleRef:
  kind: ClusterRole
  name: nodes 
  apiGroup: rbac.authorization.k8s.io

subjects:
- kind: User
  name: cluster.condi.me 
  apiGroup: rbac.authorization.k8s.io
