---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: operators

rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: operators
roleRef:
  kind: ClusterRole
  name: operators
  apiGroup: rbac.authorization.k8s.io

subjects:
- kind: Group
  name: operators
  apiGroup: rbac.authorization.k8s.io

