---
apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
  annotations:
    metallb.universe.tf/address-pool: external

spec:
  ports:
  - port: 80
    targetPort: 80
  - port: 443
    targetPort: 443
  selector:
    app: ingress-nginx
  type: LoadBalancer
