apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: internal
      protocol: arp
      arp-network: 192.168.1.0/24
      cidr:
      - 192.168.1.240/28
