apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web

spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.1.240
